#!/usr/bin/env python3

avengers = input("Who is the strongest Avenger?  ironman,  hulk,  captian america,  thor,  spiderman? ")
 
strongest_avenger = (' hulk ')

if avengers == ("hulk"):
    print(avengers + "smashes all")  

else:
    print(avengers +  "is too weak," + strongest_avenger + "is the strongest!")