#!/usr/bin/env python3

with open("dracula.txt","r") as book:
    print(book)

count = 0
for line in book:
if "vampire" in line.lower():
    print(line)
        count += 1
print(count)
~                      